### PR TITLE
Ornate spyglass

### PR DESCRIPTION
**Pull request by sipertruk**
I put the camera at visibility range so that's a maximum of 2* visibility range increase which is still less than any other far sight class spell.
As it is working we have to rotate the character to change the view : hold right click works, hold left click won't do. I'm not sure if it's possible to lock the client view angle to the character orientation?

http://web.archive.org/web/20060908170059/http://www.thottbot.com:80/?i=5420
https://wow.gamepedia.com/index.php?title=Ornate_Spyglass&oldid=89788
https://www.youtube.com/watch?v=0bfMJCOf-yI
https://www.youtube.com/watch?v=daatrrPr9qE

### CODE REVIEW

**Comment by ratkosrb** [comment]
> I'm not sure if it's possible to lock the client view angle to the character orientation?

Applying UNIT_FLAG_DISABLE_ROTATE will prevent the unit from changing orientation if that is what you need.

**Comment by sipertruk** [comment]
No I mean the client viewing angle, when you look around while holding left click you see around the updated circle which is in front of the character (nothing behind and a circle of objects in front of you). But if I remember correctly that object effect was a bit weird, maybe the reason why it was underrated.

**Comment by sipertruk** [comment]
Added information links, no vanilla era video found sadly.
http://web.archive.org/web/20060908170059/http://www.thottbot.com:80/?i=5420
https://wow.gamepedia.com/index.php?title=Ornate_Spyglass&oldid=89788
https://www.youtube.com/watch?v=0bfMJCOf-yI
https://www.youtube.com/watch?v=daatrrPr9qE

**Comment by ratkosrb** [comment]
I tested both with your changes and the development branch, and it works the same on both. Was the point to make it so creatures further away are visible when you zoom in? That's the only thing i noticed. Also changing the view works with both mouse keys for me, on both branches.

Actually i am not sure i even see creatures further away, i think they just moved.

**Comment by sipertruk** [comment]
The point of this item is to make you able to see further.
On the development branch you're only zooming on your regular view because Aura::FarSight is just a copy/paste of Aura::HandleBindSight that has no effect on the camera position (SetView on GetTarget()==caster because it's not a targeted spell).
Here's how I see it with this patch : I can see guards at Gadget's wall and birds at some giant bones that I couldn't see otherwise https://youtu.be/hMjWNW1zLaU

**Pull request merged**
