### PR TITLE
Love is in the Air

### PR DESCRIPTION
**Pull request by ratkosrb**

### CODE REVIEW

**Comment by GuybrushGit** [comment]
- Removed the fixes that have already been applied on the main branch.
- Completed DB transition for all the guards and citizens.
- Fixed crafting the city collections consuming double the reagents.
- Fixed the chocolate items not having a duration.
- Removed Black Dress from the forbidden list so it can drop.

TODO:
- Add the possibility of making secondary vendor menus.
- ACTION_T_SET_UNIT_FIELD needs a parameter to add the new value to the previous value instead of overriding it
- Find out why the city collection buffs arent stacking.
- Test Neeru Fireblade

**Comment by ratkosrb** [comment]
Oh wow! You did a lot of work.

If you want you can make an event script with SCRIPT_COMMAND_FIELD_SET or SCRIPT_COMMAND_MODIFY_FLAGS and call that from EventAI using ACTION_T_EVENT_SCRIPT, if those can do what ACTION_T_SET_UNIT_FIELD cannot. I have not updated the script editor yet so it doesn't have conditions and the latest 2 commands i added, but you can do the field/flag setting there. I spent some time making sure it gives you a list of all the correct flags depending on the flag field type you selected for command 4.

flags

Just adding the extra parameter you need to the EventAI action is more straightforward though. I actually have been making plans to rework EventAI totally and make it use the same commands as the event scripts, like they do in TrinityCore with their SmartScripts. But it will be a while until i get that done obviously, so you can just update the action command for now.

My ideas are to split the table in two:

- creature_ai_events
Will contain all the event specific data, and 3 script ids for each action.

- creature_ai_scripts
Will contain the action scripts referenced from the other table, it will be just like `gossip_scripts` and the rest.

This way in EventAI in ProcessAction all that code for processing the commands can be replaced with simply m_creature->GetMap()->ScriptStart(action_script[i]) and things will be nice and uniform.

After i do that you'll be able to edit all database scripts in the Script Editor, including EventAI. It will be super easy to script anything in the database. I can just add a separate window for browsing the AI events, and each one will have a button to load the used script Id in the other window.

**Comment by GuybrushGit** [comment]
How do you think we should do the secondary vendor menu? An "id" column on the npc_vendor table?

**Comment by ratkosrb** [comment]
That sounds good, i can think of a few different designs.

1. Adding an Id column to `npc_vendor` like you suggested, and having action_menu_id be the vendor menu number when option_id is set to GOSSIP_OPTION_VENDOR in `gossip_menu_option`.

2. Making items from the `npc_vendor_template` assigned to the `creature_template` entry show up in a separate vendor menu, instead of items from both that and `npc_vendor` table showing up in the same menu. Then we'll need to add a new option to option_id that will make the `npc_vendor_template` menu show up: GOSSIP_OPTION_VENDOR_TEMPLATE = 18.

3. Making it so that `action_menu_id` != 0 is a specific `npc_vendor_template` entry when option_id is set to GOSSIP_OPTION_VENDOR.

The first and third design would allow for unlimited number of vendor menus for each NPC. With the third option there would be the least data duplication, as we can use the same `npc_vendor_template` for all the innkeepers, provided they are supposed to sell the same items. I have not looked much at the vendor code though, so i don't know which would be easier to implement.

**Pull request merged**
